In [1]:
# check row count change
import pandas as pd

clean_scores = pd.read_csv("../outputs/clean_scores.csv")
clean_attendance = pd.read_csv("../outputs/clean_attendance.csv")
clean_demographics = pd.read_csv("../outputs/clean_demographics.csv")


print("Scores:", clean_scores.shape)
print("Attendance:", clean_attendance.shape)
print("Demographics:", clean_demographics.shape)

Scores: (5134, 26)
Attendance: (83645, 9)
Demographics: (1230, 13)

/var/folders/hs/fgtpkc7n7gg59wjjycgjmqv80000gn/T/ipykernel_63051/1055036160.py:5: DtypeWarning: Columns (0: Student ID) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_attendance = pd.read_csv("../outputs/clean_attendance.csv")

In [2]:
clean_scores["Student ID"].head(20)

0     100500
1     SI1730
2     100501
3     SI1732
4     100017
5     100068
6     SI1439
7     100016
8     100040
9     100042
10    100082
11    101096
12    100038
13    100148
14    100147
15    100018
16    101275
17    101276
18    101279
19    101281
Name: Student ID, dtype: str

In [3]:
clean_scores[
    clean_scores["Student ID"].str.startswith("SI")
].shape

(31, 26)

In [4]:
clean_scores["Score"].value_counts().head()

Score
100.0    644
70.0     283
80.0     272
75.0     215
85.0     213
Name: count, dtype: int64

In [6]:
clean_attendance.duplicated(
    subset=[
        "Student ID",
        "Date",
        "Volunteer Job: Volunteer Job Name"
    ]
).sum()

np.int64(0)

In [6]:
attendance_summary = pd.read_csv(
    "../outputs/attendance_summary.csv"
)

attendance_summary.head()

  Student ID  Total_Attendance_Records  Present_Count  Attendance Rate
0     100208                       103             54        52.427184
1     100209                        18              4        22.222222
2     100210                       103             56        54.368932
3     100211                       103             53        51.456311
4     100212                       103             51        49.514563

In [8]:
clean_scores["Assessment Improvement"].describe()

count    1742.000000
mean       21.783456
std        26.983905
min       -40.000000
25%         0.000000
50%        23.330000
75%        40.000000
max        83.890000
Name: Assessment Improvement, dtype: float64

In [9]:
clean_scores[
    [
        "Total Score(Pre-assessment)",
        "Total Score(Post-assessment)",
        "Assessment Improvement"
    ]
].dropna().head(20)

,Total Score(Pre-assessment),Total Score(Post-assessment),Assessment Improvement
40,50.00,83.33,33.33
41,53.33,30.00,-23.33
42,16.67,23.33,6.66
44,73.33,66.67,-6.66
47,46.67,36.67,-10.00
48,43.33,70.00,26.67
49,13.33,23.33,10.00
50,33.33,100.00,66.67
52,26.67,26.67,0.00
53,23.33,40.00,16.67
54,33.33,3.33,-30.00
55,33.33,100.00,66.67
56,40.00,40.00,0.00
57,53.33,30.00,-23.33
58,43.33,70.00,26.67
59,16.67,83.33,66.66
60,23.33,40.00,16.67
61,46.67,36.67,-10.00
63,16.67,23.33,6.66
65,50.00,83.33,33.33

In [10]:
clean_scores[
    [
        "Total Score(Pre-assessment)",
        "Total Score(Post-assessment)"
    ]
].notna().sum()

Total Score(Pre-assessment)     2891
Total Score(Post-assessment)    1965
dtype: int64

In [12]:
import pandas as pd

clean_scores = pd.read_csv("../outputs/clean_scores.csv")
clean_attendance = pd.read_csv("../outputs/clean_attendance.csv")
clean_demographics = pd.read_csv("../outputs/clean_demographics.csv")
attendance_summary = pd.read_csv("../outputs/attendance_summary.csv")

/var/folders/hs/fgtpkc7n7gg59wjjycgjmqv80000gn/T/ipykernel_63051/1459439131.py:4: DtypeWarning: Columns (0: Student ID) have mixed types. Specify dtype option on import or set low_memory=False.
  clean_attendance = pd.read_csv("../outputs/clean_attendance.csv")

In [13]:
print(clean_scores.shape)
print(clean_attendance.shape)
print(clean_demographics.shape)
print(attendance_summary.shape)

(5134, 26)
(83645, 10)
(1230, 13)
(1116, 4)

In [14]:
(clean_scores["Score"] == 0).sum()

np.int64(0)

In [15]:
clean_attendance.duplicated(
    subset=[
        "Student ID",
        "Date",
        "Volunteer Job: Volunteer Job Name"
    ]
).sum()

np.int64(0)

In [16]:
clean_scores["Assessment Improvement"].describe()

count    1742.000000
mean       21.783456
std        26.983905
min       -40.000000
25%         0.000000
50%        23.330000
75%        40.000000
max        83.890000
Name: Assessment Improvement, dtype: float64

## Cleaning Validation Summary

The cleaning pipeline was validated after execution. The processed datasets maintained expected structures and removed invalid records based on sponsor guidance.

Key validations:
- Missing Student IDs were removed from student-level datasets.
- Score records with Score = 0 were removed because they represent students who did not participate in assessments.
- Duplicate attendance records were removed using Student ID, Date, and Volunteer Job Name.
- Assessment improvement metrics were successfully generated from valid pre/post assessment records.

In [17]:
# Final missing value check

print("Scores missing values:")
display(clean_scores.isnull().sum())

print("Attendance missing values:")
display(clean_attendance.isnull().sum())

print("Demographics missing values:")
display(clean_demographics.isnull().sum())

Scores missing values:

Student ID                                  0
Teacher Id                               1619
Program Owner: Full Name                    0
Assignment                                936
Score                                    1284
Attendance Percentage                     217
Total Pre-assessment Score               1731
Total Score(Pre-assessment)              2243
Total Post-assessment Score              2565
Pre -Assessment Earning Income Score     1992
Post-Assessment Earning Income Score     3158
Pre -Assessment Investing Score          1990
Post-Assessment Investing Score          3170
Pre-Assessment Managing Credit Score     1992
Post-Assessment Managing Credit Score    3169
Pre-Assessment Saving Score              1992
Post-Assessment Saving Score             3169
Pre-Assessment Spending Score            1992
Post-Assessment Spending Score           3158
Pre-Assessment Managing Risk Score       2003
Post-Assessment Managing Risk Score      3158
Program Code                               33
Status                                      0
Total Score(Post-assessment)             3169
Program Name                                0
Assessment Improvement                   3392
dtype: int64

Attendance missing values:

Program Code                           103
Program Owner: Full Name                 0
Student ID                               0
Created Date                             0
Status                                   0
Attendance Status                        0
Volunteer Job: Volunteer Job Name    53974
Date                                     0
Program Name                             0
Present_Flag                             0
dtype: int64

Demographics missing values:

Student ID                      0
Last Name                       0
Contact Record Type             0
Class Year                      1
Age Group                     129
Ethnicity                       0
Gender                        102
Language                      114
Household Annual Income       104
Household Size                102
Parents Educational Degree    102
Created Date                    0
Student Email                 164
dtype: int64